default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  host: <%=  ENV['MYSQL_CHAT_HOST'] || 'localhost' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWROD'] || '12345' %>

development:
  <<: *default
  database: task-management_mysql_development

test:
  <<: *default
  database: task-management_mysql_test

production:
  <<: *default
  database: task-management_mysql_production
