development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: task-management_mysql_development
  pool: 5
  username: root
  password: 123456
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: task-management_mysql_test
  pool: 5
  username:
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: task-management_mysql_production
  pool: 5
  username:
  password:
  socket: 127.0.0.1
